services:
  - type: web
    name: unilink1
    runtime: node
    buildCommand: npm install --legacy-peer-deps && npm run build && cd server && npm install && npm run build
    startCommand: cd server && npm start
    envVars:
      - key: NODE_VERSION
        value: 18.18.0
